---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  config:
    xff_num_trusted_hops: 2
    use_remote_address: false
    resolver: {{ .Values.resolver.name | quote }}
    load_balancer:
      policy: "round_robin"
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: {{ .Values.ambassador.hostname | quote }}
spec:
  hostname: {{ .Values.ambassador.hostname | quote }}
  acmeProvider:
    authority: None
  requestPolicy:
    insecure:
      action: Route
